// This file is auto-generated by Payload.
// Add any custom component entries here, or run `pnpm payload generate:importmap` to regenerate.
import { S3ClientUploadHandler as S3ClientUploadHandler_0 } from '@payloadcms/storage-s3/client'

export const importMap = {
  '@payloadcms/storage-s3/client#S3ClientUploadHandler': S3ClientUploadHandler_0,
}
